name: pemanen_mobile
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  path: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/